/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_spc_mmfpeghello_NativeMethods */

#ifndef _Included_com_example_spc_mmfpeghello_NativeMethods
#define _Included_com_example_spc_mmfpeghello_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_spc_mmfpeghello_NativeMethods
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_spc_mmfpeghello_NativeMethods_helloWorld
  (JNIEnv *, jobject);
/*
 * Class:     com_example_spc_mmfpeghello_NativeMethods
 * Method:    urlprotocolinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_spc_mmfpeghello_NativeMethods_urlprotocolinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_example_spc_mmfpeghello_NativeMethods
 * Method:    avformatinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_spc_mmfpeghello_NativeMethods_avformatinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_example_spc_mmfpeghello_NativeMethods
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_spc_mmfpeghello_NativeMethods_avcodecinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_example_spc_mmfpeghello_NativeMethods
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_spc_mmfpeghello_NativeMethods_avfilterinfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
